---
    # configure munge
    - shell: create-munge-key < /dev/null creates=/etc/munge/munge.key
      when: not munge_key.stat.exists
    - service: name=munge state=restarted
      when: not munge_key.stat.exists

    - lineinfile: dest={{ SLURM_CONF }} regexp='ControlMachine=' line='ControlMachine={{ansible_hostname}}'
    - lineinfile: dest={{ SLURM_CONF }} regexp='NodeName=' line='NodeName={{slurm_vnode_prefix}}[1-{{slurm_wn_ips|length}}] CPUs=1 State=UNKNOWN'
      when: "{{slurm_wn_ips|length}} > 0"
    - lineinfile: dest={{ SLURM_CONF }} regexp='PartitionName=' line='PartitionName=debug Nodes={{slurm_vnode_prefix}}[1-{{slurm_wn_ips|length}}] Default=YES MaxTime=INFINITE State=UP'
      when: "{{slurm_wn_ips|length}} > 0"

    # start SLURM daemon
    - service: name={{SLURM_SERVICE}} state=started
    
    - name: Ensure slurmd is not running in front node
      command: pgrep slurmd && killall slurmd

    - shell: scontrol reconfig
