---
    # configure munge
    - shell: create-munge-key < /dev/null creates=/etc/munge/munge.key
    - service: name=munge state=restarted

    - lineinfile: dest={{ SLURM_CONF }} regexp='ControlMachine=' line='ControlMachine={{ansible_hostname}}'
    - lineinfile: dest={{ SLURM_CONF }} regexp='NodeName=' line='NodeName={{slurm_vnode_prefix}}[1-{{slurm_wn_ips|length}}] CPUs=1 State=UNKNOWN'
      when: "{{slurm_wn_ips|length}} > 0"
    - lineinfile: dest={{ SLURM_CONF }} regexp='PartitionName=' line='PartitionName={{slurm_vnode_prefix}}[1-{{slurm_wn_ips|length}}] Default=YES MaxTime=INFINITE State=UP'
      when: "{{slurm_wn_ips|length}} > 0"

    # start SLURM slurmctld daemon
    - service: name=slurm-llnl state=started
      when: ansible_os_family == "Debian"

    - name: start SLURM slurmctld daemon in RedHat systems
      command: systemctl start slurm 
      when: ansible_os_family == "RedHat"

    - shell: scontrol reconfig
