---
    # configure munge
    - shell: create-munge-key < /dev/null creates=/etc/munge/munge.key
      when: not munge_key.stat.exists
    - service: name=munge state=restarted
      when: not munge_key.stat.exists

    - name: Create the slurm.conf file
      template: dest={{ SLURM_CONF }} src=slurm.conf.j2

    # start SLURM daemon
    - service: name={{SLURM_SERVICE}} state=started
      notify: restart slurm
    
    - name: Ensure slurmd is not running in front node
      shell: pgrep slurmd && killall slurmd
      ignore_errors: yes
