---
    #SLURM dependences 
    - include: "{{ansible_os_family}}.yaml"

    # install munge
    - apt: name=munge update_cache=yes cache_valid_time=3600
      when: ansible_os_family == "Debian"
    - yum: name=munge
      when: ansible_os_family == "RedHat"
    - file: path=/var/log/munge state=directory mode=0700
    - file: path=/var/log state=directory mode=0755

    - include: "{{slurm_type_of_node}}.yaml"


