---
    # install munge
    - name: Start Munge service
      service: name=munge state=started
      register: munge_installed
      ignore_errors: yes

    - include: munge.yaml
      when: munge_installed|failed

    - stat: path=/etc/munge/munge.key
      register: munge_key

    - name: Set the ip of the slurmserver
      lineinfile: dest=/etc/hosts regexp="{{slurm_server_name}}" line="{{slurm_server_ip}} {{slurm_server_name}}.localdomain {{slurm_server_name}}"

    - include: "{{ansible_os_family}}.yaml"

    - include: "{{slurm_type_of_node}}.yaml"


